### ISSUE TITLE
Build Warning: Layout 'none' requested in assets/tipuesearch/tipuesearch_content.js does not exist.

### ISSUE THREAD

**Issue by HorlogeSkynet** [jekylltools/jekyll-tipue-search#11]
Hello !

I've just updated the search asset to your latest version (Tipue Search 6.1).
But it looks like Jekyll does not like the `layout: none` in _tipuesearch_content.js_ : 

![image](https://user-images.githubusercontent.com/5331869/27431459-e7ca5390-574c-11e7-8fa6-3d60facb2342.png)

I've changed to `layout: null` and now it does not complain anymore 👌

Let me know what you think about that.

(A big thanks for this module, it's just awesome 💯)

++

**Comment by jekylltools** [comment]
Thanks for your kind words! Support for `layout: none` was [released in Jekyll 3.5](https://jekyllrb.com/docs/history/#minor-enhancements-v3-5-0) so I'm guessing previous versions of Jekyll will throw that warning. `layout: none` is useful because it will [not be over-ridden by `defaults`](https://github.com/jekyll/jekyll/pull/5933).

However if you're running a version of Jekyll older than 3.5, your fix of `layout: null` is fine, or you can just remove the `layout` front-matter variable entirely. I'll make a note of that in the documentation.

Thanks!

**Comment by jekylltools** [comment]
Interesting, in my testing with Jekyll 3.5 I am getting the same error as you, I wonder if this is a bug in how they implemented https://github.com/jekyll/jekyll/pull/5933

**Comment by HorlogeSkynet** [comment]
Hey, thanks for your answer(s). This looks a bit weird indeed.
Actually, it's not currently possible to upgrade Jekyll to 3.5 with `npm`, so yeah the version's running here is below.

👍 for 2 or 3 words about that in the documentation 😉 

I'll let you close this issue when you think it'll be okay (waiting for Jekyll fixes ?), bye 👋

**Comment by jekylltools** [comment]
> 👍 for 2 or 3 words about that in the documentation 😉

done: https://github.com/jekylltools/jekyll-tipue-search#build-warnings-referencing-layout-none

**Comment by jekylltools** [comment]
@HorlogeSkynet turns out there was a bug in Jekyll so it will be fixed however I learned that `layout: none` isn't actually useful here, and I also learned that asset files are not included into layouts, so we don't need to declare any layout variable at all. so thanks again, you helped me to better understand how jekyll renders pages, and thus we can simplify this module by completely removing layout: none! 🎉

**Comment by HorlogeSkynet** [comment]
I'm glad it helped !
Thanks again, see you 👋
